name: Sync to Emergency-USB-Kit

on:
  schedule:
    - cron: '0 5,17 * * *'  # Runs at 5 AM and 5 PM UTC daily
  push:
    branches:
      - main  # Also runs immediately when you push
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Server-Scripts
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Server-Scripts
          token: ${{ secrets.PAT }}
          path: Server-Scripts
      
      - name: Sync Server-Scripts
        run: |
          mkdir -p "emergency-usb-kit/EmergencyUSB/Scripts/Server-Scripts/"
          find "emergency-usb-kit/EmergencyUSB/Scripts/Server-Scripts/" -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' Server-Scripts/ "emergency-usb-kit/EmergencyUSB/Scripts/Server-Scripts/"

      - name: Checkout Health-Library
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Health-Library
          token: ${{ secrets.PAT }}
          path: Health-Library
      
      - name: Sync Server-Scripts
        run: |
          mkdir -p "emergency-usb-kit/EmergencyUSB/Docs/Health-Library/"
          find "emergency-usb-kit/EmergencyUSB/Docs/Health-Library/" -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' Health-Library/ "emergency-usb-kit/EmergencyUSB/Docs/Health-Library"
          
      - name: Commit and push changes
        run: |
          cd emergency-usb-kit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync updates from multiple repos - $(date)"
            git push
          fi
